### PR TITLE
Make YamlError an Exception, makes for easier interop

### PR DESCRIPTION
**Pull request by sideeffffect**

### CODE REVIEW

**Comment by lbialy** [comment]
A little bit left there, some tests to check positionality of errors. I'll
get to this.

**Comment by sideeffffect** [comment]
So technically there may result conflicts with these two PRs.

In spirit they are not in conflict, right? They don't go against each other, if I understood it correctly. Nor do I have any problem with the aim of that other PR.

But this PR is much simpler and can be merged and released right now, which would unblock me in a downstream project. Would it be possible to merge and release this toady, please @tgodzik @lbialy  ?

**Comment by lbialy** [comment]
Let me take a quick look.

**Review by lbialy — APPROVED** [review]

**Comment by lbialy** [comment]
yeah, it's fine

**Comment by lbialy** [comment]
@tgodzik will you handle the release or should I? do we do snapshots here?

**Comment by tgodzik** [comment]
Versions 0.1.0 is running, but we do release snapshots.

**Pull request merged**
