### PR TITLE
Reenable Scala 3 Native build, drop to Scala 3.1.3

### PR DESCRIPTION
**Pull request by keynmol**
Additionally, fix errors on ~older~ Scala 3

I was hitting the following errors:

```scala
[error] -- Error: /Users/velvetbaldmime/projects/scala-yaml/core/shared/src/test/scala-3/org/virtuslab/yaml/BaseYamlEncoderSuite.scala:28:54
[error] 28 |    case class Data(int: Int, double: Double) derives YamlCodec
[error]    |                                                      ^
[error]    |undefined: YamlEncoderCrossCompanionCompat_this.deriveProduct # -1: TermRef(TermRef(NoPrefix,val YamlEncoderCrossCompanionCompat_this),deriveProduct) at inlining
[error]    |---------------------------------------------------------------------------
[error]    |Inline stack trace
[error]    |- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
[error]    |This location contains code that was inlined from YamlEncoderCrossCompat.scala:8
[error]  8 |    case p: Mirror.ProductOf[T] => deriveProduct(p)
[error]    |                                   ^^^^^^^^^^^^^
[error]     ---------------------------------------------------------------------------
[error] one error found
[error] (core / Test / compileIncremental) Compilation failed
```

Not sure if it's a regression on Scala 3 or what, but I think it'd be prudent to have a 3.1.x release first.

### CODE REVIEW

**Comment by keynmol** [comment]
@lwronski @kpodsiad whenever you have time :)

Would be good to get both a SN 3 release, but also to not have to bump to Scala 3.2.x as it's just been released and it would force upgrades.

**Comment by armanbilge** [comment]
👍 I'm the one that bumped to Scala 3.2 and temporarily dumped Native in https://github.com/VirtusLab/scala-yaml/pull/162#discussion_r915912903 because I obviously didn't have what it takes to power through the compile issues ... happy to see this reverted.

**Review by lwronski — APPROVED** [review]

**Comment by lwronski** [comment]
@keynmol LGTM, Thanks for contributing!

**Comment by armanbilge** [comment]
Nice! Would be great if we can get a release with this soon :)

**Comment by lwronski** [comment]
> Nice! Would be great if we can get a release with this soon :)

Yea, thanks again for your contributions, scala-yaml `0.0.5` is available in maven - https://repo1.maven.org/maven2/org/virtuslab/scala-yaml_3/0.0.5/

**Pull request merged**
